file_name = "C:\Users\vppit\Desktop\Sorbonne\M_S3\AM\TP\Vents\Impédances\cylindre-embout\Impedance.txt";

[f, real_imp, imag_imp] = importfile(file_name, [1, Inf]);

idx = f>=150;


% Cylindre
%zn    = [63.3, 19.9, 9.2, 5.6];
%wn    = 2.*pi.*[443, 1341, 2238, 3143];
%Qn    = [50, 50, 37, 35];

% Cylindre pailles
%zn    = [13.1, 6., 4.1, 2.2, 1.6];
%wn    = 2.*pi.*[419, 1300, 2219, 3080, 3991];
%Qn    = [10, 15, 20, 16, 10];

% Cylindre embout 
zn    = [42.7, 17.2, 13.9, 9.7, 8.0, 4.4, 5.1];
wn    = 2.*pi.*[252, 779, 1309, 1864, 2425, 3014, 3585];
Qn    = [30, 50, 60, 55, 58, 40, 55];

% Cylindre embout pailles
%zn    = [15.5, 5.8, 5.3, 3.8, 4., 1.5, 2.8];
%wn    = 2.*pi.*[249, 742, 1281, 1820, 2386, 2933, 3540];
%Qn    = [10, 13, 22, 23, 31, 17, 30];


Z_theo = give_Z_theo(zn, wn, Qn,2*pi*f);


plot(f(idx),real_imp(idx),'b-','DisplayName', '\sl{R}(Z_{exp})');
hold on
plot(f(idx),imag_imp(idx),'r-','DisplayName', '\sl{Im}(Z_{exp})');
hold on
plot(f(idx),real(Z_theo(idx)),'b--','DisplayName', '\sl{R}(Z_{theo})');
hold on
plot(f(idx),imag(Z_theo(idx)),'r--','DisplayName', '\sl{Im}(Z_{theo})');

legend('fontsize',12)
xlabel('f (Hz)','fontsize',14) ;


%% Fonctions

function Z = give_Z_theo(zn, wn, Qn, w)

Z = zeros(1,length(w));

for i=1:length(zn)
    Z = Z + zn(i).*1i.*w.*wn(i)./Qn(i)...
        ./(wn(i).^2 + 1j.*w.*wn(i)./Qn(i) - w.^2);
end

end




function [f, mod, arg] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [F, MOD, ARG] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [F, MOD, ARG] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [f, mod, arg] = importfile("C:\Users\vppit\Desktop\Sorbonne\M_S3\AM\TP\Vents\Impédances\cylindre\Impedance.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Nov-2023 13:09:02

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["f", "mod", "arg"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
f = tbl.f;
mod = tbl.mod;
arg = tbl.arg;
end